### ISSUE TITLE
cp.multitap.genTaps.expDelay is limited to 256 taps

### ISSUE THREAD

**Issue by tmhglnd** [composingcap/cpDelayNetworks#1]
The zl objects in the abstractions limit the number of taps to 256 due to the default `zlmaxsize` of 256. This probably also stretches down to the `cp.multitap~`

**Comment by composingcap** [comment]
- Updated cp.multitap.genTaps.expDelay to adjust zlmaxsize with the size of of the generated list
- Updated cp.multitap.genTaps.comby to have a max size of  32767
- Updated cp.multitap~ to check length of lists and set zl sizes (there are now three zl.len with a max size of 32767)

- [x] Does listfunnel have a max size less than max's stack? -- **It does not**

[updated commit](https://github.com/composingcap/cpDelayNetworks/commit/e639f623747f2abdd6f7641cd0cdfcb096b798a1)
